### ISSUE TITLE
Retirar do alarme o modo soneca e repetir

### ISSUE THREAD

**Issue by otaviotarelho** [otaviotarelhodb/Tempus#3]
Verificar o código e tentar não comprometer a criação do alarme. Não alterar a classe de alarmes. Setar essas areas como NULL

**Comment by diegonunesreis** [comment]
Não apaguei nada, só comentei os bagulhos

**Comment by otaviotarelho** [comment]
Só verifica se os alarms continuam funcionando haha

**Comment by diegonunesreis** [comment]
funfa
