### ISSUE TITLE
Fornecer dados do mapa na função de tempo do criar alarme.

### ISSUE THREAD

**Issue by otaviotarelho** [otaviotarelhodb/Tempus#4]
Puxar os dados daquela função que retorna -1, caso não consiga dados retornar -1

**Comment by diegonunesreis** [comment]
funciona, mas ao clicar pra salvar o alarme precisa dar confirm  naquela mensagem de "nao foi possivel calcular o tempo"  pelo menos 3 vezes. Não to entendendo que porra ta acontecendo, parece que ele só chama a expectedTimeOfArrivel() depois que confirma a mensagem de erro, sei la que merda ta acontecendo.

**Comment by otaviotarelho** [comment]
Depois eu vou dar uma olhada, mas provavelmente não está alterando a variável que controla a mensagem no Dialog.
