### ISSUE TITLE
Corrigir linguagem

### ISSUE THREAD

**Issue by otaviotarelho** [otaviotarelhodb/Tempus#7]
Fazer linguagem se ajustar automaticamente, 
apagar o menu de seleção de linguagem,
verificar os itens de seleção nas activities e no manifest.xml,
Verificar se o time picker e os relógios se ajustam automaticamente quando setado para 12h

**Comment by diegonunesreis** [comment]
tudo certo

**Comment by otaviotarelho** [comment]
Não funciona quando vc troca a linguagem do sistema.
